cmake_minimum_required(VERSION 4.1)
project(Stock_market_simulation)

set(CMAKE_CXX_STANDARD 14)

include_directories(cpp_sim)
include_directories(venv/Lib/site-packages/numpy/_core/include)
include_directories(venv/Lib/site-packages/numpy/_core/include/numpy)
include_directories(venv/Lib/site-packages/numpy/_core/include/numpy/random)
include_directories(venv/Lib/site-packages/numpy/f2py/src)
include_directories(venv/Lib/site-packages/pyarrow)
include_directories(venv/Lib/site-packages/pyarrow/include)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/acero)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/adapters)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/adapters/orc)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/adapters/tensorflow)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/array)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/c)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/compute)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/compute/row)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/csv)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/dataset)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/engine)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/engine/substrait)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/extension)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/filesystem)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/flight)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/io)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/ipc)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/json)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/python)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/python/vendored)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/tensor)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/testing)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/util)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/vendored)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/vendored/datetime)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/vendored/double-conversion)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/vendored/pcg)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/vendored/portable-snippets)
include_directories(venv/Lib/site-packages/pyarrow/include/arrow/vendored/xxhash)
include_directories(venv/Lib/site-packages/pyarrow/include/parquet)
include_directories(venv/Lib/site-packages/pyarrow/include/parquet/api)
include_directories(venv/Lib/site-packages/pyarrow/include/parquet/arrow)
include_directories(venv/Lib/site-packages/pyarrow/include/parquet/encryption)
include_directories(venv/Lib/site-packages/pyarrow/include/parquet/geospatial)
include_directories(venv/Lib/site-packages/pyarrow/src/arrow/python)
include_directories(venv/Lib/site-packages/pyarrow/src/arrow/python/vendored)

add_executable(Stock_market_simulation
        cpp_sim/Agent.h
        cpp_sim/AgentType.h
        cpp_sim/AggressiveAgent.cpp
        cpp_sim/AggressiveAgent.h
        cpp_sim/CommonFunctions.h
        cpp_sim/ConservativeAgent.cpp
        cpp_sim/ConservativeAgent.h
        cpp_sim/Error.h
        cpp_sim/Logger.h
        cpp_sim/main.cpp
        cpp_sim/Market.cpp
        cpp_sim/Market.h
        cpp_sim/MarketStats.h
        cpp_sim/Order.h
        cpp_sim/OrderBook.cpp
        cpp_sim/OrderBook.h
        cpp_sim/OrderType.h
        cpp_sim/ScenarioConfig.cpp
        cpp_sim/ScenarioConfig.h
        cpp_sim/Trade.h
        venv/Lib/site-packages/fastparquet/cencoding.c
        venv/Lib/site-packages/fastparquet/speedups.c
        venv/Lib/site-packages/fontTools/cu2qu/cu2qu.c
        venv/Lib/site-packages/fontTools/feaLib/lexer.c
        venv/Lib/site-packages/fontTools/misc/bezierTools.c
        venv/Lib/site-packages/fontTools/pens/momentsPen.c
        venv/Lib/site-packages/fontTools/qu2cu/qu2cu.c
        venv/Lib/site-packages/fontTools/varLib/iup.c
        venv/Lib/site-packages/numpy/_core/include/numpy/random/bitgen.h
        venv/Lib/site-packages/numpy/_core/include/numpy/random/distributions.h
        venv/Lib/site-packages/numpy/_core/include/numpy/random/libdivide.h
        venv/Lib/site-packages/numpy/_core/include/numpy/__multiarray_api.c
        venv/Lib/site-packages/numpy/_core/include/numpy/__multiarray_api.h
        venv/Lib/site-packages/numpy/_core/include/numpy/__ufunc_api.c
        venv/Lib/site-packages/numpy/_core/include/numpy/__ufunc_api.h
        venv/Lib/site-packages/numpy/_core/include/numpy/_neighborhood_iterator_imp.h
        venv/Lib/site-packages/numpy/_core/include/numpy/_numpyconfig.h
        venv/Lib/site-packages/numpy/_core/include/numpy/_public_dtype_api_table.h
        venv/Lib/site-packages/numpy/_core/include/numpy/arrayobject.h
        venv/Lib/site-packages/numpy/_core/include/numpy/arrayscalars.h
        venv/Lib/site-packages/numpy/_core/include/numpy/dtype_api.h
        venv/Lib/site-packages/numpy/_core/include/numpy/halffloat.h
        venv/Lib/site-packages/numpy/_core/include/numpy/ndarrayobject.h
        venv/Lib/site-packages/numpy/_core/include/numpy/ndarraytypes.h
        venv/Lib/site-packages/numpy/_core/include/numpy/npy_2_compat.h
        venv/Lib/site-packages/numpy/_core/include/numpy/npy_2_complexcompat.h
        venv/Lib/site-packages/numpy/_core/include/numpy/npy_3kcompat.h
        venv/Lib/site-packages/numpy/_core/include/numpy/npy_common.h
        venv/Lib/site-packages/numpy/_core/include/numpy/npy_cpu.h
        venv/Lib/site-packages/numpy/_core/include/numpy/npy_endian.h
        venv/Lib/site-packages/numpy/_core/include/numpy/npy_math.h
        venv/Lib/site-packages/numpy/_core/include/numpy/npy_no_deprecated_api.h
        venv/Lib/site-packages/numpy/_core/include/numpy/npy_os.h
        venv/Lib/site-packages/numpy/_core/include/numpy/numpyconfig.h
        venv/Lib/site-packages/numpy/_core/include/numpy/ufuncobject.h
        venv/Lib/site-packages/numpy/_core/include/numpy/utils.h
        venv/Lib/site-packages/numpy/_core/tests/data/generate_umath_validation_data.cpp
        venv/Lib/site-packages/numpy/_core/tests/examples/limited_api/limited_api1.c
        venv/Lib/site-packages/numpy/_core/tests/examples/limited_api/limited_api_latest.c
        venv/Lib/site-packages/numpy/f2py/src/fortranobject.c
        venv/Lib/site-packages/numpy/f2py/src/fortranobject.h
        venv/Lib/site-packages/numpy/f2py/tests/src/array_from_pyobj/wrapmodule.c
        venv/Lib/site-packages/pyarrow/include/arrow/acero/accumulation_queue.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/aggregate_node.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/api.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/asof_join_node.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/backpressure_handler.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/benchmark_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/bloom_filter.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/exec_plan.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/hash_join.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/hash_join_dict.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/hash_join_node.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/map_node.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/options.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/order_by_impl.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/partition_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/query_context.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/schema_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/task_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/test_nodes.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/time_series_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/tpch_node.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/util.h
        venv/Lib/site-packages/pyarrow/include/arrow/acero/visibility.h
        venv/Lib/site-packages/pyarrow/include/arrow/adapters/orc/adapter.h
        venv/Lib/site-packages/pyarrow/include/arrow/adapters/orc/options.h
        venv/Lib/site-packages/pyarrow/include/arrow/adapters/tensorflow/convert.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/array_base.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/array_binary.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/array_decimal.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/array_dict.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/array_nested.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/array_primitive.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/array_run_end.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/builder_adaptive.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/builder_base.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/builder_binary.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/builder_decimal.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/builder_dict.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/builder_nested.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/builder_primitive.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/builder_run_end.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/builder_time.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/builder_union.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/concatenate.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/data.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/diff.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/statistics.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/util.h
        venv/Lib/site-packages/pyarrow/include/arrow/array/validate.h
        venv/Lib/site-packages/pyarrow/include/arrow/c/abi.h
        venv/Lib/site-packages/pyarrow/include/arrow/c/bridge.h
        venv/Lib/site-packages/pyarrow/include/arrow/c/dlpack.h
        venv/Lib/site-packages/pyarrow/include/arrow/c/dlpack_abi.h
        venv/Lib/site-packages/pyarrow/include/arrow/c/helpers.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/row/grouper.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/api.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/api_aggregate.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/api_scalar.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/api_vector.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/cast.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/exec.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/expression.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/function.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/function_options.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/initialize.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/kernel.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/ordering.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/registry.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/util.h
        venv/Lib/site-packages/pyarrow/include/arrow/compute/visibility.h
        venv/Lib/site-packages/pyarrow/include/arrow/csv/api.h
        venv/Lib/site-packages/pyarrow/include/arrow/csv/chunker.h
        venv/Lib/site-packages/pyarrow/include/arrow/csv/column_builder.h
        venv/Lib/site-packages/pyarrow/include/arrow/csv/column_decoder.h
        venv/Lib/site-packages/pyarrow/include/arrow/csv/converter.h
        venv/Lib/site-packages/pyarrow/include/arrow/csv/invalid_row.h
        venv/Lib/site-packages/pyarrow/include/arrow/csv/options.h
        venv/Lib/site-packages/pyarrow/include/arrow/csv/parser.h
        venv/Lib/site-packages/pyarrow/include/arrow/csv/reader.h
        venv/Lib/site-packages/pyarrow/include/arrow/csv/test_common.h
        venv/Lib/site-packages/pyarrow/include/arrow/csv/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/arrow/csv/writer.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/api.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/dataset.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/dataset_writer.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/discovery.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/file_base.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/file_csv.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/file_ipc.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/file_json.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/file_orc.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/file_parquet.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/parquet_encryption_config.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/partition.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/plan.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/projector.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/scanner.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/arrow/dataset/visibility.h
        venv/Lib/site-packages/pyarrow/include/arrow/engine/substrait/api.h
        venv/Lib/site-packages/pyarrow/include/arrow/engine/substrait/extension_set.h
        venv/Lib/site-packages/pyarrow/include/arrow/engine/substrait/extension_types.h
        venv/Lib/site-packages/pyarrow/include/arrow/engine/substrait/options.h
        venv/Lib/site-packages/pyarrow/include/arrow/engine/substrait/relation.h
        venv/Lib/site-packages/pyarrow/include/arrow/engine/substrait/serde.h
        venv/Lib/site-packages/pyarrow/include/arrow/engine/substrait/test_plan_builder.h
        venv/Lib/site-packages/pyarrow/include/arrow/engine/substrait/test_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/engine/substrait/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/arrow/engine/substrait/util.h
        venv/Lib/site-packages/pyarrow/include/arrow/engine/substrait/visibility.h
        venv/Lib/site-packages/pyarrow/include/arrow/engine/api.h
        venv/Lib/site-packages/pyarrow/include/arrow/extension/bool8.h
        venv/Lib/site-packages/pyarrow/include/arrow/extension/fixed_shape_tensor.h
        venv/Lib/site-packages/pyarrow/include/arrow/extension/json.h
        venv/Lib/site-packages/pyarrow/include/arrow/extension/opaque.h
        venv/Lib/site-packages/pyarrow/include/arrow/extension/uuid.h
        venv/Lib/site-packages/pyarrow/include/arrow/filesystem/api.h
        venv/Lib/site-packages/pyarrow/include/arrow/filesystem/azurefs.h
        venv/Lib/site-packages/pyarrow/include/arrow/filesystem/filesystem.h
        venv/Lib/site-packages/pyarrow/include/arrow/filesystem/filesystem_library.h
        venv/Lib/site-packages/pyarrow/include/arrow/filesystem/gcsfs.h
        venv/Lib/site-packages/pyarrow/include/arrow/filesystem/hdfs.h
        venv/Lib/site-packages/pyarrow/include/arrow/filesystem/localfs.h
        venv/Lib/site-packages/pyarrow/include/arrow/filesystem/mockfs.h
        venv/Lib/site-packages/pyarrow/include/arrow/filesystem/path_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/filesystem/s3_test_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/filesystem/s3fs.h
        venv/Lib/site-packages/pyarrow/include/arrow/filesystem/test_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/filesystem/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/api.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/client.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/client_auth.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/client_cookie_middleware.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/client_middleware.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/client_tracing_middleware.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/middleware.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/otel_logging.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/platform.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/server.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/server_auth.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/server_middleware.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/server_tracing_middleware.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/test_auth_handlers.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/test_definitions.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/test_flight_server.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/test_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/transport.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/transport_server.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/types.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/types_async.h
        venv/Lib/site-packages/pyarrow/include/arrow/flight/visibility.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/api.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/buffered.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/caching.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/compressed.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/concurrency.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/file.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/hdfs.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/interfaces.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/memory.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/mman.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/slow.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/stdio.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/test_common.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/transform.h
        venv/Lib/site-packages/pyarrow/include/arrow/io/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/arrow/ipc/api.h
        venv/Lib/site-packages/pyarrow/include/arrow/ipc/dictionary.h
        venv/Lib/site-packages/pyarrow/include/arrow/ipc/feather.h
        venv/Lib/site-packages/pyarrow/include/arrow/ipc/message.h
        venv/Lib/site-packages/pyarrow/include/arrow/ipc/options.h
        venv/Lib/site-packages/pyarrow/include/arrow/ipc/reader.h
        venv/Lib/site-packages/pyarrow/include/arrow/ipc/test_common.h
        venv/Lib/site-packages/pyarrow/include/arrow/ipc/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/arrow/ipc/util.h
        venv/Lib/site-packages/pyarrow/include/arrow/ipc/writer.h
        venv/Lib/site-packages/pyarrow/include/arrow/json/api.h
        venv/Lib/site-packages/pyarrow/include/arrow/json/chunked_builder.h
        venv/Lib/site-packages/pyarrow/include/arrow/json/chunker.h
        venv/Lib/site-packages/pyarrow/include/arrow/json/converter.h
        venv/Lib/site-packages/pyarrow/include/arrow/json/from_string.h
        venv/Lib/site-packages/pyarrow/include/arrow/json/object_parser.h
        venv/Lib/site-packages/pyarrow/include/arrow/json/object_writer.h
        venv/Lib/site-packages/pyarrow/include/arrow/json/options.h
        venv/Lib/site-packages/pyarrow/include/arrow/json/parser.h
        venv/Lib/site-packages/pyarrow/include/arrow/json/rapidjson_defs.h
        venv/Lib/site-packages/pyarrow/include/arrow/json/reader.h
        venv/Lib/site-packages/pyarrow/include/arrow/json/test_common.h
        venv/Lib/site-packages/pyarrow/include/arrow/json/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/vendored/pythoncapi_compat.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/api.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/arrow_to_pandas.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/async.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/benchmark.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/common.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/config.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/csv.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/datetime.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/decimal.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/extension_type.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/filesystem.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/flight.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/gdb.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/helpers.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/inference.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/io.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/ipc.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/iterators.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/lib.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/lib_api.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/numpy_convert.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/numpy_init.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/numpy_interop.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/numpy_to_arrow.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/parquet_encryption.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/platform.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/pyarrow.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/pyarrow_api.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/pyarrow_lib.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/python_test.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/python_to_arrow.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/type_traits.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/udf.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/util.h
        venv/Lib/site-packages/pyarrow/include/arrow/python/visibility.h
        venv/Lib/site-packages/pyarrow/include/arrow/tensor/converter.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/async_test_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/builder.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/executor_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/extension_type.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/fixed_width_test_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/future_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/generator.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/gtest_compat.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/gtest_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/matchers.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/math.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/process.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/random.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/uniform_real.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/util.h
        venv/Lib/site-packages/pyarrow/include/arrow/testing/visibility.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/algorithm.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/align_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/aligned_storage.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/async_generator.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/async_generator_fwd.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/async_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/base64.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/basic_decimal.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/benchmark_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/binary_view_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/bit_block_counter.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/bit_run_reader.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/bit_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/bitmap.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/bitmap_builders.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/bitmap_generate.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/bitmap_ops.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/bitmap_reader.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/bitmap_visit.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/bitmap_writer.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/byte_size.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/cancel.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/checked_cast.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/compare.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/compression.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/concurrent_map.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/config.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/converter.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/cpu_info.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/crc32.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/debug.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/decimal.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/delimiting.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/endian.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/float16.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/formatting.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/functional.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/future.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/hash_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/hashing.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/int_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/int_util_overflow.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/io_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/iterator.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/key_value_metadata.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/launder.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/list_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/logger.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/logging.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/macros.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/math_constants.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/mutex.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/parallel.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/pcg_random.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/prefetch.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/queue.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/range.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/ree_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/regex.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/rows_to_batches.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/secure_string.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/simd.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/small_vector.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/span.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/string.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/string_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/task_group.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/test_common.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/thread_pool.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/time.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/tracing.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/type_traits.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/ubsan.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/union_util.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/unreachable.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/uri.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/utf8.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/value_parsing.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/vector.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/visibility.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/windows_compatibility.h
        venv/Lib/site-packages/pyarrow/include/arrow/util/windows_fixup.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/datetime/date.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/datetime/ios.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/datetime/tz.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/datetime/tz_private.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/datetime/visibility.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/double-conversion/bignum-dtoa.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/double-conversion/bignum.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/double-conversion/cached-powers.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/double-conversion/diy-fp.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/double-conversion/double-conversion.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/double-conversion/double-to-string.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/double-conversion/fast-dtoa.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/double-conversion/fixed-dtoa.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/double-conversion/ieee.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/double-conversion/string-to-double.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/double-conversion/strtod.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/double-conversion/utils.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/pcg/pcg_extras.hpp
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/pcg/pcg_random.hpp
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/pcg/pcg_uint128.hpp
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/portable-snippets/debug-trap.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/portable-snippets/safe-math.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/xxhash/xxhash.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/datetime.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/ProducerConsumerQueue.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/strptime.h
        venv/Lib/site-packages/pyarrow/include/arrow/vendored/xxhash.h
        venv/Lib/site-packages/pyarrow/include/arrow/api.h
        venv/Lib/site-packages/pyarrow/include/arrow/array.h
        venv/Lib/site-packages/pyarrow/include/arrow/buffer.h
        venv/Lib/site-packages/pyarrow/include/arrow/buffer_builder.h
        venv/Lib/site-packages/pyarrow/include/arrow/builder.h
        venv/Lib/site-packages/pyarrow/include/arrow/chunk_resolver.h
        venv/Lib/site-packages/pyarrow/include/arrow/chunked_array.h
        venv/Lib/site-packages/pyarrow/include/arrow/compare.h
        venv/Lib/site-packages/pyarrow/include/arrow/config.h
        venv/Lib/site-packages/pyarrow/include/arrow/datum.h
        venv/Lib/site-packages/pyarrow/include/arrow/device.h
        venv/Lib/site-packages/pyarrow/include/arrow/device_allocation_type_set.h
        venv/Lib/site-packages/pyarrow/include/arrow/extension_type.h
        venv/Lib/site-packages/pyarrow/include/arrow/memory_pool.h
        venv/Lib/site-packages/pyarrow/include/arrow/memory_pool_test.h
        venv/Lib/site-packages/pyarrow/include/arrow/pretty_print.h
        venv/Lib/site-packages/pyarrow/include/arrow/record_batch.h
        venv/Lib/site-packages/pyarrow/include/arrow/result.h
        venv/Lib/site-packages/pyarrow/include/arrow/scalar.h
        venv/Lib/site-packages/pyarrow/include/arrow/sparse_tensor.h
        venv/Lib/site-packages/pyarrow/include/arrow/status.h
        venv/Lib/site-packages/pyarrow/include/arrow/stl.h
        venv/Lib/site-packages/pyarrow/include/arrow/stl_allocator.h
        venv/Lib/site-packages/pyarrow/include/arrow/stl_iterator.h
        venv/Lib/site-packages/pyarrow/include/arrow/table.h
        venv/Lib/site-packages/pyarrow/include/arrow/table_builder.h
        venv/Lib/site-packages/pyarrow/include/arrow/tensor.h
        venv/Lib/site-packages/pyarrow/include/arrow/type.h
        venv/Lib/site-packages/pyarrow/include/arrow/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/arrow/type_traits.h
        venv/Lib/site-packages/pyarrow/include/arrow/visit_array_inline.h
        venv/Lib/site-packages/pyarrow/include/arrow/visit_data_inline.h
        venv/Lib/site-packages/pyarrow/include/arrow/visit_scalar_inline.h
        venv/Lib/site-packages/pyarrow/include/arrow/visit_type_inline.h
        venv/Lib/site-packages/pyarrow/include/arrow/visitor.h
        venv/Lib/site-packages/pyarrow/include/arrow/visitor_generate.h
        venv/Lib/site-packages/pyarrow/include/parquet/api/io.h
        venv/Lib/site-packages/pyarrow/include/parquet/api/reader.h
        venv/Lib/site-packages/pyarrow/include/parquet/api/schema.h
        venv/Lib/site-packages/pyarrow/include/parquet/api/writer.h
        venv/Lib/site-packages/pyarrow/include/parquet/arrow/reader.h
        venv/Lib/site-packages/pyarrow/include/parquet/arrow/schema.h
        venv/Lib/site-packages/pyarrow/include/parquet/arrow/test_util.h
        venv/Lib/site-packages/pyarrow/include/parquet/arrow/writer.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/crypto_factory.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/encryption.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/file_key_material_store.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/file_key_unwrapper.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/file_key_wrapper.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/file_system_key_material_store.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/key_encryption_key.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/key_material.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/key_metadata.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/key_toolkit.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/kms_client.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/kms_client_factory.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/local_wrap_kms_client.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/test_encryption_util.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/test_in_memory_kms.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/two_level_cache_with_expiration.h
        venv/Lib/site-packages/pyarrow/include/parquet/encryption/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/parquet/geospatial/statistics.h
        venv/Lib/site-packages/pyarrow/include/parquet/benchmark_util.h
        venv/Lib/site-packages/pyarrow/include/parquet/bloom_filter.h
        venv/Lib/site-packages/pyarrow/include/parquet/bloom_filter_reader.h
        venv/Lib/site-packages/pyarrow/include/parquet/column_page.h
        venv/Lib/site-packages/pyarrow/include/parquet/column_reader.h
        venv/Lib/site-packages/pyarrow/include/parquet/column_scanner.h
        venv/Lib/site-packages/pyarrow/include/parquet/column_writer.h
        venv/Lib/site-packages/pyarrow/include/parquet/encoding.h
        venv/Lib/site-packages/pyarrow/include/parquet/exception.h
        venv/Lib/site-packages/pyarrow/include/parquet/file_reader.h
        venv/Lib/site-packages/pyarrow/include/parquet/file_writer.h
        venv/Lib/site-packages/pyarrow/include/parquet/hasher.h
        venv/Lib/site-packages/pyarrow/include/parquet/level_comparison.h
        venv/Lib/site-packages/pyarrow/include/parquet/level_comparison_inc.h
        venv/Lib/site-packages/pyarrow/include/parquet/level_conversion.h
        venv/Lib/site-packages/pyarrow/include/parquet/level_conversion_inc.h
        venv/Lib/site-packages/pyarrow/include/parquet/metadata.h
        venv/Lib/site-packages/pyarrow/include/parquet/page_index.h
        venv/Lib/site-packages/pyarrow/include/parquet/parquet_version.h
        venv/Lib/site-packages/pyarrow/include/parquet/platform.h
        venv/Lib/site-packages/pyarrow/include/parquet/printer.h
        venv/Lib/site-packages/pyarrow/include/parquet/properties.h
        venv/Lib/site-packages/pyarrow/include/parquet/schema.h
        venv/Lib/site-packages/pyarrow/include/parquet/size_statistics.h
        venv/Lib/site-packages/pyarrow/include/parquet/statistics.h
        venv/Lib/site-packages/pyarrow/include/parquet/stream_reader.h
        venv/Lib/site-packages/pyarrow/include/parquet/stream_writer.h
        venv/Lib/site-packages/pyarrow/include/parquet/test_util.h
        venv/Lib/site-packages/pyarrow/include/parquet/type_fwd.h
        venv/Lib/site-packages/pyarrow/include/parquet/types.h
        venv/Lib/site-packages/pyarrow/include/parquet/windows_compatibility.h
        venv/Lib/site-packages/pyarrow/include/parquet/windows_fixup.h
        venv/Lib/site-packages/pyarrow/include/parquet/xxhasher.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/vendored/pythoncapi_compat.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/api.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/arrow_to_pandas.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/arrow_to_pandas.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/arrow_to_python_internal.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/async.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/benchmark.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/benchmark.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/common.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/common.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/config.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/config.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/csv.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/csv.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/datetime.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/datetime.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/decimal.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/decimal.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/extension_type.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/extension_type.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/filesystem.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/filesystem.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/flight.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/flight.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/gdb.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/gdb.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/helpers.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/helpers.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/inference.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/inference.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/io.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/io.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/ipc.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/ipc.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/iterators.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/numpy_convert.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/numpy_convert.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/numpy_init.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/numpy_init.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/numpy_internal.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/numpy_interop.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/numpy_to_arrow.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/numpy_to_arrow.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/parquet_encryption.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/parquet_encryption.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/platform.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/pyarrow.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/pyarrow.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/pyarrow_api.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/pyarrow_lib.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/python_test.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/python_test.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/python_to_arrow.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/python_to_arrow.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/type_traits.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/udf.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/udf.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/util.cc
        venv/Lib/site-packages/pyarrow/src/arrow/python/util.h
        venv/Lib/site-packages/pyarrow/src/arrow/python/visibility.h
        venv/Lib/site-packages/pyarrow/lib.h
        venv/Lib/site-packages/pyarrow/lib_api.h)
